### PR TITLE
design refresh

### PR DESCRIPTION
**Pull request by eeshaan**
**initial**
Screenshot_2020-05-22 Love Match Find your match (2)

**when opening pr**
Screenshot_2020-05-23 Love Match Find your match

**goal**
Desktop HD
Mobile
logo-square-9fps

### CODE REVIEW

**Comment by AtaGowani** [comment]
Screen Shot 2020-05-23 at 3 42 41 PM
Time block doesn't show as previewed. @eeshaan

**Comment by AtaGowani** [comment]
Or was that the intent?

**Comment by eeshaan** [comment]
`position: fixed` is intended

**Comment by AtaGowani** [comment]
> Or was that the intent?

Didn't read the opening message in PR. Sorry. I understand now.

**Pull request merged**
